CREATE DATABASE IF NOT EXISTS blyss CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE blyss;

CREATE TABLE IF NOT EXISTS users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, email VARCHAR(255) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, name VARCHAR(160) NOT NULL, phone VARCHAR(40), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_users_name (name)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS customer_profiles (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL UNIQUE, country VARCHAR(80) NOT NULL DEFAULT 'India', shipping_address TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS measurements (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, bust DECIMAL(8,2), under_bust DECIMAL(8,2), waist DECIMAL(8,2), shoulder DECIMAL(8,2), armhole DECIMAL(8,2), blouse_length DECIMAL(8,2), sleeve_length DECIMAL(8,2), sleeve_round DECIMAL(8,2), measurement_unit ENUM('in','cm') NOT NULL DEFAULT 'in', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_measurements_user (user_id), FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS standard_sizes (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, code VARCHAR(20) NOT NULL UNIQUE, bust DECIMAL(8,2) NOT NULL DEFAULT 0, under_bust DECIMAL(8,2), waist DECIMAL(8,2), shoulder DECIMAL(8,2), armhole DECIMAL(8,2), blouse_length DECIMAL(8,2), sleeve_length DECIMAL(8,2), sleeve_round DECIMAL(8,2), measurement_unit ENUM('in','cm') NOT NULL DEFAULT 'in') ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS blouse_designs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, category ENUM('front_neck','back_neck','sleeve') NOT NULL, name VARCHAR(120) NOT NULL, image_url VARCHAR(500), active BOOLEAN NOT NULL DEFAULT TRUE, UNIQUE KEY uq_design_category_name (category,name), INDEX idx_design_category (category,active)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS fabrics (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, fabric_type ENUM('Blyss Fabric','My Own Fabric') NOT NULL, name VARCHAR(160) NOT NULL, price DECIMAL(10,2) NOT NULL DEFAULT 0, image_url VARCHAR(500), active BOOLEAN NOT NULL DEFAULT TRUE, UNIQUE KEY uq_fabric_type_name (fabric_type,name)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS carts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED, session_token VARCHAR(128) UNIQUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_cart_user (user_id), FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS cart_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, cart_id BIGINT UNSIGNED NOT NULL, quantity INT UNSIGNED NOT NULL DEFAULT 1, configuration JSON NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (cart_id) REFERENCES carts(id) ON DELETE CASCADE, INDEX idx_cart_items_cart (cart_id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS orders (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_number VARCHAR(40) NOT NULL UNIQUE, user_id BIGINT UNSIGNED, customer_name VARCHAR(160) NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(40) NOT NULL, country VARCHAR(80) NOT NULL, shipping_address TEXT NOT NULL, fit_type ENUM('standard','custom') NOT NULL, standard_size VARCHAR(20), measurements JSON, front_neck VARCHAR(120) NOT NULL, back_neck VARCHAR(120) NOT NULL, sleeve VARCHAR(120) NOT NULL, lining VARCHAR(120) NOT NULL, padding VARCHAR(120) NOT NULL, fabric_type VARCHAR(80) NOT NULL, fabric_name VARCHAR(160), reference_image_url VARCHAR(1000), special_instructions TEXT, quantity INT UNSIGNED NOT NULL DEFAULT 1, stitching_price DECIMAL(10,2) NOT NULL DEFAULT 4800, fabric_price DECIMAL(10,2) NOT NULL DEFAULT 0, shipping_fee DECIMAL(10,2) NOT NULL DEFAULT 0, total_amount DECIMAL(10,2) NOT NULL DEFAULT 4800, currency CHAR(3) NOT NULL DEFAULT 'INR', payment_status VARCHAR(40) NOT NULL DEFAULT 'Pending Payment', order_status VARCHAR(60) NOT NULL DEFAULT 'Pending Payment', tracking_number VARCHAR(120), payment_reference VARCHAR(255) UNIQUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_orders_status_date (order_status,created_at), INDEX idx_orders_email (email), FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS order_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_id BIGINT UNSIGNED NOT NULL, quantity INT UNSIGNED NOT NULL DEFAULT 1, configuration JSON NOT NULL, unit_price DECIMAL(10,2) NOT NULL DEFAULT 4800, FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE, INDEX idx_order_items_order (order_id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS payments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_id BIGINT UNSIGNED NOT NULL, provider VARCHAR(40) NOT NULL DEFAULT 'test', payment_reference VARCHAR(255) NOT NULL UNIQUE, proof_url VARCHAR(1000), amount DECIMAL(10,2) NOT NULL, status VARCHAR(40) NOT NULL DEFAULT 'Pending', paid_at TIMESTAMP NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE, INDEX idx_payments_status (status,created_at)) ENGINE=InnoDB;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS proof_url VARCHAR(1000) AFTER payment_reference;
CREATE TABLE IF NOT EXISTS order_status_history (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_id BIGINT UNSIGNED NOT NULL, status VARCHAR(60) NOT NULL, note TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE, INDEX idx_status_history_order (order_id,created_at)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS auth_sessions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, token_hash CHAR(64) NOT NULL UNIQUE, expires_at DATETIME NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX idx_sessions_expiry (expires_at)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS admin_users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, email VARCHAR(255) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, name VARCHAR(160) NOT NULL DEFAULT 'Blyss Admin', active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS admin_sessions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, admin_user_id BIGINT UNSIGNED NOT NULL, token_hash CHAR(64) NOT NULL UNIQUE, expires_at DATETIME NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (admin_user_id) REFERENCES admin_users(id) ON DELETE CASCADE, INDEX idx_admin_sessions_expiry (expires_at)) ENGINE=InnoDB;

INSERT IGNORE INTO standard_sizes (code,bust,under_bust,waist,shoulder,armhole,blouse_length,sleeve_length,sleeve_round) VALUES ('XS',32,28,26,13,14,14,10,10),('S',34,30,28,13.5,15,14.5,10.5,10.5),('M',36,32,30,14,16,15,11,11),('L',38,34,32,14.5,17,15.5,11.5,11.5),('XL',40,36,34,15,18,16,12,12),('XXL',42,38,36,15.5,19,16.5,12.5,12.5);
INSERT IGNORE INTO blouse_designs (category,name) VALUES ('front_neck','Round Neck'),('front_neck','U Neck'),('front_neck','Deep U'),('front_neck','V Neck'),('front_neck','Deep V'),('front_neck','Square Neck'),('front_neck','Sweetheart'),('front_neck','Boat Neck'),('front_neck','High Neck'),('front_neck','Keyhole'),('front_neck','Scalloped'),('front_neck','Designer Neck'),('back_neck','U Back'),('back_neck','V Back'),('back_neck','Deep V'),('back_neck','Square Back'),('back_neck','Round Back'),('back_neck','Keyhole'),('back_neck','Dori Back'),('back_neck','Tie-up Back'),('back_neck','Cut-out Back'),('back_neck','Designer Back'),('sleeve','Sleeveless'),('sleeve','Short Sleeve'),('sleeve','Elbow Sleeve'),('sleeve','3/4 Sleeve'),('sleeve','Full Sleeve'),('sleeve','Puff Sleeve'),('sleeve','Bell Sleeve'),('sleeve','Frill Sleeve'),('sleeve','Petal Sleeve'),('sleeve','Slit Sleeve'),('sleeve','Designer Sleeve');
INSERT IGNORE INTO fabrics (fabric_type,name,price) VALUES ('Blyss Fabric','Blyss Fabric',0),('My Own Fabric','My Own Fabric',0);
